apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: "YWRtaW4=" # base64 : admin
  POSTGRES_PASSWORD: "c2VjcmV0" # base64 : secret
  POSTGRES_DB: "cG9ydGZvbGlv"
