apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend
        image: terencered/resume-service:latest
        ports:
        - containerPort: 3001
